version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output 